spring.application.name=erp

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/erp
spring.datasource.username=root
spring.datasource.password=pKavya@14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
